title: Example.com
description: "Introduction for you blog"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: example@gmail.com
github_username: github
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo:
giscus_repoId:
giscus_category:
giscus_categoryId:
goatcounter_code:
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                 #
#   Not recommended to touch the materials below  #
#                                                 #
#    Any changes may contribute to malfunction    #
#                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Build settings

# If you want to deploy Git Page, but choosing the second Installation method (described in README.md)
# rather than fork, then replace the below line with `remote_theme: byanko55/jekyll-theme-satellite`.
# Otherwise, DO NOT change it.
theme: jekyll-theme-satellite

exclude:
  - _posts

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
